modLoader="javafml"

loaderVersion="[36,)"

license="All Rights Reserved"

issueTrackerURL="https://github.com/Tiviacz1337/PizzaCraft/issues"

[[mods]]

modId="pizzacraft"

version="3.0.9"

displayName="PizzaCraft"

updateJSONURL="https://gist.githubusercontent.com/Tiviacz1337/b916e3981957f1e6f2de99ea0aa328fa/raw"

displayURL="https://www.curseforge.com/minecraft/mc-mods/pizzacraft"

authors="Tiviacz1337, SirSquidly"

description='Brings the tasty pizza to Minecraft!'

[[dependencies.pizzacraft]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.pizzacraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"